name: flutter_bloc_example
description: A project used to demo the BLoC generator
version: 1.0.0
author: Callum Iddon <iddoncallum@gmail.com>
homepage: https://github.com/CallumIddon/flutter_bloc_generator/

environment:
  sdk: ">=2.0.0-dev.68.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  flutter_bloc_annotations: 0.3.0
  flutter_bloc_provider: 0.3.0
  rxdart: ^0.19.0

dev_dependencies:
  build_runner: 1.0.0
  flutter_test:
    sdk: flutter
  flutter_bloc_generator: 0.3.0

flutter:
  uses-material-design: true