name: flutter_bloc_generator
description: Automatic BLoC generator for flutter that will generate BLoC architected code
             automatically.
version: 0.2.6
author: Callum Iddon <iddoncallum@gmail.com>
homepage: https://github.com/CallumIddon/flutter_bloc_generator/

environment:
  sdk: ">=2.0.0 <3.0.0"

dependencies:
  analyzer: ^0.33.0
  build: ^1.0.1
  source_gen: ^0.9.0
  flutter_bloc_annotations: ^0.2.6

dev_dependencies:
  build_runner: ^1.1.0