name: flutter_bloc_generator
description: Automatic BLoC generator for flutter.
version: 0.1.0
author: Callum Iddon
homepage: https://github.com/CallumIddon/flutter_bloc_generator/

environment:
  sdk: ">=2.0.0 <3.0.0"

dependencies:
  build: '>=0.12.0 <2.0.0'
  source_gen: ^0.9.0
  flutter_bloc:
    path: ../flutter_bloc/
  
dev_dependencies:
  build_runner: '>=0.9.0 <0.11.0'